[project]
name = "wizwad"
version = "0.4.4"
description = "A fast extractor and packer for wizard101/pirate101 wad files"
authors = [{ name = "StarrFox", email = "starrfox6312@gmail.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
dependencies = [
    "click>=8.1.7,<9",
    "more-itertools>=10.1.0,<11",
]

[project.urls]
Repository = "https://github.com/wizspoil/wizwad"

[project.scripts]
wizwad = "wizwad.__main__:main"

[dependency-groups]
benchmarks = [
    "scalene>=1.5.55",
]
tests = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]

[tool.uv]
default-groups = "all"

[tool.pyright]
typeCheckingMode = "strict"
reportUnusedFunction = false

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.7.22"]
build-backend = "uv_build"


